base_data = {
            "tank": {
                "level": 1,
                "player_class": "tank",
                "hp": 12,
                "mana": 0,                
                "int": 5,
                "str": 10,
                "dex": 5,
                "sta": 10,
                "xp_now": 0,
                "xp_tnl": 5,
                "x": 500,
                "y": 500,
                "last_biome":"forest",
                "equip": [],
                "items": []
                },
            "deep": {
                "level": 1,
                "player_class": "deep",
                "hp": 5,
                "mana": 10, 
                "int": 10,
                "str": 12,
                "dex": 10,
                "sta": 5,
                "xp_now": 0,
                "xp_tnl": 5,
                "x": 500,
                "y": 500,
                "last_biome":"forest",
                "equip": [],
                "items": []
                },
            "heal": {
                "level": 1,
                "player_class": "heal",
                "hp": 5,
                "mana": 20, 
                "int": 10,
                "str": 5,
                "dex": 10,
                "sta": 10,
                "xp_now": 0,
                "xp_tnl": 5,
                "x": 500,
                "y": 500,
                "last_biome":"forest",
                "equip": [],
                "items": []},
            "denk": {
                "level": 1,
                "player_class": "denk",
                "hp": 7,
                "mana": 10,
                "int": 10,
                "str": 10,
                "dex": 10,
                "sta": 10,
                "xp_now": 0,
                "xp_tnl": 5,
                "x": 500,
                "y": 500,
                "last_biome":"forest",
                "equip": [],
                "items": []},
            "heep": {
                "level": 1,
                "player_class": "deep",
                "hp": 5,
                "mana": 30, 
                "int": 15,
                "str": 5,
                "dex": 5,
                "sta": 10,
                "xp_now": 0,
                "xp_tnl": 5,
                "x": 500,
                "y": 500,
                "last_biome":"forest",
                "equip": [],
                "items": []},
            "henk": {
                "level": 1,
                "player_class": "deep",
                "hp": 12,
                "mana": 10, 
                "int": 5,
                "str": 7,
                "dex": 10,
                "sta": 12,
                "xp_now": 0,
                "xp_tnl": 5,
                "x": 500,
                "y": 500,
                "last_biome":"forest",
                "equip": [],
                "items": []},
            }
